name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Azure VM to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 20.42.105.173 >> ~/.ssh/known_hosts

      - name: Change ownership and permissions
        run: |
          ssh azureuser@ <<EOF20.42.105.173
          sudo chown -R azureuser:azureuser /var/www/html/portal
          sudo chmod -R 755 portal
          EOF
        env:
          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}

      - name: Copy files via SCP
        run: scp -r * azureuser@:20.42.105.173 /var/www/html/portal
        env:
          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}

      - name: Revert ownership to web server user
        run: |
          ssh azureuser@20.42.105.173 <<EOF
          sudo chown -R www-data:www-data /var/www/html/portal
          EOF
        env:
          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}

      - name: SSH into Azure VM and restart Apache
        run: |
          ssh azureuser@20.42.105.173 <<EOF
          sudo systemctl restart apache2
          EOF
        env:
          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}

