name: Deploy to Azure VM

on:
  push:
    branches:
      - main  # or the branch you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files via SCP
        run: scp -r * <azureuser>@<20.110.89.17>:/var/www/html/

      - name: SSH into Azure VM and restart Apache
        run: |
          ssh <sasim-it>@<20.110.89.17> <<EOF
          sudo systemctl restart apache2
          EOF
